version: '3.8'
services:
  mysql:
    image: mysql:8.0.36

    platform: linux/amd64
    volumes:
      - board_mysql_volume:/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    command:
      [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1' ]

  redis:
    image: redis:7.2
    ports:
      - '6379:6379'
    volumes:
      - board_redis_volume:/data


volumes:
  # Named Volume 컨테이너 내부 파일 시스템과 마운트 될 볼륨 위치를 알아서 잡아줌
  board_mysql_volume:
  board_redis_volume:
